[project]
name = "RepeaterBotUpdated"
version = "0.1"
dependencies = ["aiogram==3.3.0", "loguru==0.7.2", "python-dotenv==1.0.0", "pytz==2023.3.post1", "tzlocal==5.2",
                "pydantic==2.5.3"]
